version: "3.9"
services:
  logmap:
    build: ./docker/logmap
    image: graph-mesh/logmap:latest
    volumes:
      - ./artifacts:/artifacts
  aml:
    build: ./docker/aml
    image: graph-mesh/aml:latest
    volumes:
      - ./artifacts:/artifacts
  bertmap:
    build: ./docker/bertmap
    image: graph-mesh/bertmap:latest
    volumes:
      - ./artifacts:/artifacts
  orchestrator:
    build:
      context: .
      dockerfile: docker/orchestrator.Dockerfile
    image: graph-mesh/orchestrator:latest
    depends_on:
      - logmap
      - aml
      - bertmap
    volumes:
      - ./artifacts:/artifacts
      - ./data_sources:/data_sources
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["python", "-m", "graph_mesh_orchestrator.pipeline"]
    command: ["/data_sources/sample_manifest.yaml"]
