version: "3.9"
services:
  # Ontology matchers
  logmap:
    build: ./docker/logmap
    image: graph-mesh/logmap:latest
    volumes:
      - ./artifacts:/artifacts

  aml:
    build: ./docker/aml
    image: graph-mesh/aml:latest
    volumes:
      - ./artifacts:/artifacts

  bertmap:
    build: ./docker/bertmap
    image: graph-mesh/bertmap:latest
    volumes:
      - ./artifacts:/artifacts

  # XSD to OWL converter (Ontmalizer)
  ontmalizer:
    build: ./docker/ontmalizer
    image: graph-mesh/ontmalizer:latest
    volumes:
      - ./artifacts:/artifacts
    # Service container, no default command

  # Main orchestrator
  orchestrator:
    build:
      context: .
      dockerfile: docker/orchestrator.Dockerfile
    image: graph-mesh/orchestrator:latest
    depends_on:
      - logmap
      - aml
      - bertmap
      - ontmalizer
    volumes:
      - ./artifacts:/app/artifacts
      - ./data_sources:/app/data_sources
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["python", "-m", "graph_mesh_orchestrator.pipeline"]
    command: ["/data_sources/sample_manifest.yaml"]
    environment:
      - PYTHONUNBUFFERED=1
